# Generated by Django 2.2.6 on 2019-11-24 14:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('registery', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('final', models.IntegerField(default=0)),
                ('invoice_id', models.IntegerField(default=0)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property_purchased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.PropertyListing')),
            ],
        ),
    ]
