# Generated by Django 2.2.6 on 2019-12-07 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
        ('blog', '0002_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_queried', models.DateTimeField(auto_now_add=True, verbose_name='date queried')),
                ('property_interested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.PropertyListing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
