# Generated by Django 2.2.6 on 2019-11-24 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=5000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=property.models.upload_location)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=property.models.upload_location)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=property.models.upload_location)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=property.models.upload_location)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=property.models.upload_location)),
                ('image6', models.ImageField(blank=True, null=True, upload_to=property.models.upload_location)),
                ('image7', models.ImageField(blank=True, null=True, upload_to=property.models.upload_location)),
                ('address', models.CharField(default=False, max_length=200)),
                ('city', models.CharField(default=False, max_length=100)),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TS', 'Telangana'), ('TR', 'Tripura'), ('UK', 'Uttrakhand'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal'), ('AN', 'Andaman and Nicobar Islands'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('LH', 'Ladakh')], default=False, max_length=25)),
                ('zipcode', models.IntegerField(default=False)),
                ('description', models.TextField(blank=True, default=False)),
                ('price', models.IntegerField(default=False)),
                ('bedrooms', models.IntegerField(default=False)),
                ('latitude', models.FloatField(default='32.1111')),
                ('longitude', models.FloatField(default='32.1111')),
                ('bathrooms', models.IntegerField(default=False)),
                ('sqft', models.IntegerField(default=False)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('year_built', models.IntegerField(default=0)),
                ('types', models.CharField(choices=[('R', 'Rent'), ('S', 'Sell'), ('B', 'Both')], default='R', max_length=1)),
                ('premium', models.CharField(choices=[('Y', 'yes'), ('N', 'No')], default='N', max_length=1)),
                ('pool', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('gym', models.BooleanField()),
                ('balcony', models.BooleanField()),
                ('stay', models.CharField(choices=[('A', 'Apartment'), ('H', 'House')], default='H', max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
