# Generated by Django 2.2.6 on 2019-12-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='Verify',
            field=models.CharField(choices=[('V', 'Verified'), ('N', 'Not Verified'), ('R', 'rejected')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='area',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
